### ISSUE TITLE
silent failures in scripts

### ISSUE THREAD

**Issue by qoijjj** [blue-build/cli#97] opened 2024-02-27 18:26 UTC
When a build contains a script that has failures, the build succeeds anyways:

https://github.com/secureblue/secureblue/actions/runs/8068238477/job/22040501361

**Comment by gmpinder** [comment] 2024-02-27 19:34
Please either link the exact line in the log or paste the error you are seeing

**Comment by qoijjj** [comment] 2024-02-27 19:36
@gmpinder on second thought, is the `chmod` is not actually failing at all? Is it succeeding but then being reverted by bluebuild somehow?

**Comment by qoijjj** [comment] 2024-02-27 19:36
I was assuming it was failing since it's not persisting into the resulting image. But you're right it's not the only option.

**Comment by gmpinder** [comment] 2024-02-27 19:46
The only explicit one we're doing is https://github.com/blue-build/cli/blob/main/template/templates/modules/modules.j2#L22C3-L22C51

You can run `bluebuild template <recipe_path>` to see what the resulting Containerfile looks like so you can inspect it. We are making use of some bind mounts to try to reduce bloat in the final image, but that wouldn't be messing with anything in `/usr/bin`

**Comment by gmpinder** [comment] 2024-02-27 20:19
Closing as duplicate of #100

**Closed by gmpinder** 2024-02-27 20:19 UTC
Labels: duplicate
